indent-for-nested-containers-with-the-same-orientation = 30
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
non-empty-workspaces-root-containers-layout-on-startup = 'smart'
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[workspace-to-monitor-force-assignment]
0 = 'built-in'
1 = 'built-in'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#on-window-detected-callback
# TODO: Update on release 0.6.0-Beta

## windows that should float
# [[on-window-detected]]
# app-id = 'com.apple.systempreferences'
# run = 'layout floating'
# [[on-window-detected]]
# app-id = 'com.bitwarden.desktop'
# run = 'layout floating'
# [[on-window-detected]]
# app-id = 'net.ankiweb.dtop'
# run = 'layout floating'

## move to (s)ocial workspace
# [[on-window-detected]]
# app-id = 'com.tdesktop.Telegram'
# run = ['layout floating', 'move-node-to-workspace S']
# [[on-window-detected]]
# app-id = 'com.apple.MobileSMS'
# run = ['layout floating', 'move-node-to-workspace S']
# [[on-window-detected]]
# app-id = 'Mattermost.Desktop'
# run = ['layout floating', 'move-node-to-workspace S']
# [[on-window-detected]]
# app-id = 'ZoomChat'
# run = ['layout floating', 'move-node-to-workspace S']
# [[on-window-detected]]
# app-id = 'Signal'
# run = ['layout floating', 'move-node-to-workspace S']
# [[on-window-detected]]
# app-id = 'com.hnc.Discord'
# run = ['layout floating', 'move-node-to-workspace S']

## move to (m)ultimedia workspace
# [[on-window-detected]]
# app-id = 'com.apple.Music'
# run = ['layout floating', 'move-node-to-workspace M']
# [[on-window-detected]]
# app-id = 'com.apple.podcasts'
# run = ['layout floating', 'move-node-to-workspace M']
# [[on-window-detected]]
# app-id = 'org.videolan.vlc'
# run = ['layout floating', 'move-node-to-workspace M']

[mode.main.binding]
# replace with fn
alt-space = 'exec-and-forget $(bash ~/.dotfiles/scripts/toggle_app.bash "WezTerm")'
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-f = 'fullscreen'
alt-r = 'reload-config'
# alt-ctrl-cmd-b = 'exec-and-forget $(sketchybar --reload)'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through up'
alt-shift-l = 'move-through right'

alt-right = 'resize smart -50'
alt-left = 'resize smart +50'

alt-0 = 'workspace 0'
# avoid collision until fn works again
f1 = 'workspace 1'
f2 = 'workspace 2'
f3 = 'workspace 3'
f4 = 'workspace 4'
f5 = 'workspace 5'
f6 = 'workspace 6'
f7 = 'workspace 7'
f8 = 'workspace 8'
f9 = 'workspace 9'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
# alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
#alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
# alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
# alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-q = 'move-node-to-workspace Q'
# alt-shift-r = 'move-node-to-workspace R'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-z = 'move-node-to-workspace Z'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor next'

alt-shift-backspace = 'mode service'
[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
esc = 'mode main'

alt-shift-comma = 'mode join'
[mode.join.binding]
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
esc = ['reload-config', 'mode main']
